language: python
dist: bionic
cache:
  pip: true
addons:
  apt:
    packages:
      - libxkbcommon-x11-0
      - libosmesa6
      - libglx-mesa0
      - libopengl0
      - libglx0
      - libdbus-1-3

env:
    global: PYTHON_VERSION=3.7 DISPLAY=:99.0
            
jobs:

  allow_failures:
    - os: osx
    - os: windows
    
  include:
    - name: "Python 3.7 on Bionic Linux"
      os: linux
      python: "3.7"
      before_install:
        - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
            /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
            fi;
        - python -m pip install --upgrade pip
        - pip install vtk xvfbwrapper
        - pip install -r requirements.txt
        - pip install black
        - black --check .
        - pip install --upgrade "pytest<5.4" pytest-sugar pytest-cov pytest-mock pytest-timeout
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.3  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
        - python3 -m pip install --user --upgrade pip
        - pip3 install --user vtk xvfbwrapper
        - pip3 install --user -r requirements.txt
        - pip3 install --user black
        - black --check .
        - pip3 install --user --upgrade "pytest<5.4" pytest-sugar pytest-cov pytest-mock pytest-timeout
      install:
        - python3 setup.py install
    - name: "Python 3.7 on Windows 10"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
        - python -m pip install --user --upgrade pip
        - pip install --user vtk xvfbwrapper
        - pip install --user -r requirements.txt
        - pip install --user black
        - black --check .
        - pip install --user --upgrade "pytest<5.4" pytest-sugar pytest-cov pytest-mock pytest-timeout
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH      
 
install:
  - python setup.py install

script:
  - pytest ./tests
  - pytest --cov=bfieldtools ./tests
  
after_script:
  - bash <(curl -s https://codecov.io/bash)
